# Generated by Django 5.1.4 on 2025-01-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_person_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="role",
            field=models.EmailField(max_length=254),
        ),
    ]
